Fixed extra args

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -30,12 +30,25 @@ jobs:
           sudo apt-get install -y python3-dev cmake g++ ninja-build
           python -m pip install --upgrade pip nanobind
           pip install --upgrade setuptools wheel
-
-      - name: Configure and Build
+      - name: Run clang-tidy on C++ files
         run: |
-          mkdir -p build
+          set -e  # Exit immediately if any command fails
           cd build
-          cmake ..
-          cmake --build . --config Release -j $(nproc)
-          cd ..
-          python setup.py build_ext
+          echo "Running clang-tidy linting process..."
+          
+          # Determine NANOBIND Includes
+          NANOBIND_INCLUDES=$(python3 -c "import nanobind; print(nanobind.include_dir())")
+          echo "NANOBIND_INCLUDES: $NANOBIND_INCLUDES"
+
+          # Determine Python Includes
+          PYTHON_INCLUDES=$(python3-config --includes | tr ' ' '\n' | grep "^-I" | sed 's/^-I//')
+          echo "PYTHON_INCLUDES: $PYTHON_INCLUDES"
+
+          # Prepare Complete Include Arguments for clang-tidy
+          INCLUDE_ARGS=$(echo $PYTHON_INCLUDES $NANOBIND_INCLUDES | xargs -I{} echo --extra-arg="-I{}" | tr '\n' ' ')
+          echo "INCLUDE_ARGS: $INCLUDE_ARGS"
+
+          # Run clang-tidy
+          find ../pyTGM -type f \( -name '*.cpp' \) | xargs -I{} clang-tidy -p . {} $INCLUDE_ARGS || true
+
+          echo "clang-tidy process finished."
